### ISSUE TITLE
Todo list for frontend

### ISSUE THREAD

**Issue by stefnotch** [YouSafe/shifty-maze#3]
- [x] Actual interactions (need the backend)
- [x] Getting data from the backend (same)
- [x] Game settings below the start game (board size dropdown, and items-per-player input field?)
- [x] Rendering the rows/column things that one can click on
- [x] Rendering the free tile in one of the corners
- [x] Tweak rendering to handle multiple pieces on one tile
- [x] More visible active cards highlight
- [x] Highlight searched-for piece
- [x] De-saturate or sepia the emojis
- [x] Test on mobile
- [ ] Stretch goals: 
  - [x] Undo button in one of the corners
  - [ ] WebRTC communication
  - [x] Store game in local storage
