### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by stefnotch** [YouSafe/shifty-maze#4]
- [ ] Tile inserting (two step thingy, because a tile can be rotated before inserting)
- [x] Generating items
- [x] Shifting tiles
- [x] Highlighting player start positions
- [ ] (Simplifying code pls)
- [ ] Testing it
